#
# Copyrights to StackInsights
# All rights are reserved 2019
#

load("@rules_proto//proto:defs.bzl", "proto_library")

package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # StackInsights 2

proto_library(
  name = "common_protocol_proto_lib",
  srcs = ["Common.proto"],
)
